### ISSUE TITLE
unkown streamId: cowbells

### ISSUE THREAD

**Issue by paritoshmmmec** [Blackmist/csharp-storm-example#1]
[Context.CheckInputSchema()] unkown streamId: cowbells

This is what I am getting after running the sample ,This is first time I am trying to run this sample

**Comment by Blackmist** [comment]
Were you using the local test? If so, this is expected - SCP.Net local mode doesn't currently support multiple streams and will generate errors.

I just committed a new version to remove local tests to prevent confusion.

**Comment by paritoshmmmec** [comment]
thanks a lot
